site :opscode

cookbook 'apt'
cookbook 'python'
cookbook 'rbenv'
cookbook 'golang'
cookbook 'nodejs'
cookbook 'php'
cookbook 'java'
cookbook 'groovy'
cookbook 'maven', git: 'git@github.com:soundcloud-cookbooks/maven.git'
cookbook 'dnsmasq', git: 'git://github.com/maxlinc/dnsmasq.git', branch: "hash_merge"
cookbook 'ssh_known_hosts'
cookbook 'users'
cookbook 'sudo'
