Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.communicator = :winrm
  config.winrm.transport = :ssl
  config.winrm.ssl_peer_verification = false
  config.winrm.username = 'Administrator'
  config.winrm.password = ENV['WINRM_PASS']
  # Disable synced folders, or set it to something that will work on Windows
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision :shell, :path => 'scripts/windows/setup.ps1'

  # Scripts from packer-windows to setup rsync since we don't have good synced_folder options
  # config.vm.provision :shell, :path => 'scripts/windows/openssh.ps1'
  # config.vm.provision :shell, :path => 'scripts/windows/rsync.bat'

  config.vm.provision :shell, :path => 'scripts/windows/test_on_windows.ps1'

  config.vm.provider :rackspace do |rs|
    rs.username = ENV['RAX_USERNAME']
    rs.api_key  = ENV['RAX_API_KEY']
    rs.rackspace_region   = ENV['RAX_REGION']
    rs.admin_password = ENV['WINRM_PASS']
    rs.flavor   = /2 GB General Purpose v1/
    rs.image    = 'Windows Server 2012'
    rs.init_script = File.read 'bootstrap.cmd'
  end
end
