#!/bin/bash
gem install bundler --no-ri --no-rdoc
rbenv rehash
bundle update
virtualenv polytrix
source polytrix/bin/activate
export PATH="$PATH:`pwd`/node_modules/.bin"
bundle exec rake bootstrap
cp -r doc-src docs/
