#!/bin/bash
set -e
bundle exec rake clean bootstrap spec documentation:dashboard
bundle exec rspec spec/phase2/feature_coverage_report.rb --format MatrixFormatter::Formatters::HTML5Formatter --out docs/api_coverage.html
